-- Exercici 1: Creació de perfils, rols i usuaris (grup 02)

-- 1. PERFILS
CREATE PROFILE perfil_test LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME UNLIMITED
    SESSIONS_PER_USER UNLIMITED;

CREATE PROFILE perfil_dev LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 270   -- 9 mesos
    SESSIONS_PER_USER 4;

CREATE PROFILE perfil_gestor LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 270
    SESSIONS_PER_USER 4;

-- 2. ROLS
CREATE ROLE rol_test;
GRANT CREATE SESSION TO rol_test;
GRANT SELECT ANY TABLE TO rol_dev; -- comprovar

CREATE ROLE rol_dev;
GRANT CREATE SESSION TO rol_dev;
GRANT SELECT ANY TABLE TO rol_dev;
GRANT INSERT ANY TABLE TO rol_dev;
GRANT UPDATE ANY TABLE TO rol_dev;
GRANT DELETE ANY TABLE TO rol_dev;
GRANT EXECUTE ANY PROCEDURE TO rol_dev;

CREATE ROLE rol_gestor;
GRANT CREATE SESSION TO rol_gestor;
GRANT SELECT ANY TABLE TO rol_gestor;
GRANT INSERT ANY TABLE TO rol_gestor;
GRANT UPDATE ANY TABLE TO rol_gestor;
GRANT DELETE ANY TABLE TO rol_gestor;
GRANT EXECUTE ANY PROCEDURE TO rol_gestor;

-- 3. USUARIS
CREATE USER usuariTest IDENTIFIED BY grup02 PROFILE perfil_test;
GRANT rol_test TO usuariTest;
ALTER USER usuariTest DEFAULT ROLE rol_test;

CREATE USER usuariDev IDENTIFIED BY grup02 PROFILE perfil_dev;
GRANT rol_dev TO usuariDev;
ALTER USER usuariDev DEFAULT ROLE rol_dev;

CREATE USER usuariGestor IDENTIFIED BY grup02 PROFILE perfil_gestor;
GRANT rol_gestor TO usuariGestor;
ALTER USER usuariGestor DEFAULT ROLE rol_gestor;

-- 4. PRIVILEGIS DIRECTES PER A GESTOR
GRANT CREATE TABLE TO usuariGestor;
GRANT CREATE SEQUENCE TO usuariGestor;
GRANT CREATE TRIGGER TO usuariGestor;
GRANT CREATE PROCEDURE TO usuariGestor;

-- 5. TABLESPACE I QUOTA
ALTER USER usuariGestor DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER usuariDev DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER usuariTest DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
